### PR TITLE
GH-198: FTP Server: rely on the OS-selected port

### PR DESCRIPTION
**Pull request by artembilan**
Fixes spring-projects/spring-integration-samples#198

The `SocketUtils.findAvailableServerSocket()` isn't reliable for port selection and its `socket.close()` may cause a port selection by some other process.

### CODE REVIEW

**Comment by garyrussell** [comment]
Update SSHD to 1.4?

Also, I see ftpserver-core 1.1.0 is available.

**Comment by artembilan** [comment]
Good idea!
Also I see some problems with Spring Boot 2.0 compatibility.

**Comment by garyrussell** [comment]
This is good; thanks - perhaps we should consider moving the (S)FTP test support classes to spring-integration-test (like we did with the mail server).

A different PR, though.

**Comment by artembilan** [comment]
> A different PR, though.

??? That is a different project anyway...
I thought about that as well when fixed Java DSL project.
Plus I guess Spring Cloud Stream would get a gain from that `spring-integration-test` foundation pretty well.
And, of course, SI AWS or any similar in the future...

**Comment by garyrussell** [comment]
Merged as ea919aa4be0fea8061b2594e1046cd1aca9512c4

**Pull request closed without merging**
