### PR TITLE
INTEXT-191: Add Apache Kafka Sample

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/INTEXT-191

### CODE REVIEW

**Comment by artembilan** [comment]
Merging with simple polishing and rebasing...

**Comment by artembilan** [comment]
I thought that it would be so easy just polish a bit and re-generate poms and merge, but looks like Gradle 2.5 (or Groovy 2.3 >) doesn't like `build {}` block for the `generatePom` task: https://discuss.gradle.org/t/after-upgrade-gradle-to-2-0-version-the-maven-pom-not-support-build-property/2190/3.

Don't you, @garyrussell , remember if we faced and overcame somehow something similar in other projects?

**Comment by garyrussell** [comment]
The last time I generated poms; I dropped gradle back to 1.9 (temporarily - just for the generate) - I didn't have time to figure out how to get it to work with a more recent gradle.

**Comment by artembilan** [comment]
@garyrussell , I found how to fix it for the Gradle 2.x: https://github.com/artembilan/spring-integration-samples/commit/12a94e0508a0cc9301f0e751bdae51c0ad3535d8

Let me know if you have any concerns and I can merge it.
Thanks

**Comment by garyrussell** [comment]
Cool; good work; go ahead.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-integration-samples/commit/ecab656cc15f2067c548c7dbdfdcfcc5a512cda3

**Pull request closed without merging**
