### PR TITLE
Add Java DSL sample for Kafka 0.9

### PR DESCRIPTION
**Pull request by artembilan**

### CODE REVIEW

**Comment by artembilan** [comment]
Do not merge yet. 
Looks like Spring Integration doesn't support gateway for message polling: https://jira.spring.io/browse/INT-4070

**Comment by artembilan** [comment]
Now it can be morged.

**Comment by garyrussell** [comment]
We should probably wait until Monday and 4.3.1.RELEASE rather than having a sample based on a snapshot.

**Comment by artembilan** [comment]
@garyrussell , is there something wrong with this PR?
Or can I go ahead and merge it myself?

Altough, I agree that it might worth to re-test it against your latest SK-1.1 upgrade....

**Comment by garyrussell** [comment]
Confused - there's a commit - "upgrade to 4.3.1.BS" which doesn't do that - did you change that commit after my comment above?

**Comment by artembilan** [comment]
Oh! That one! I think that is just typo from my side.
I definitely upgraded it to the `RELEASE`.
But right now it does not make sense after merging your change #175 .

Although after all this upgrades I think we still have to regenerate all poms.

Are you going to do that on merge or should I push it here as well ?

**Comment by garyrussell** [comment]
Please push - coffee time for me 😄

**Pull request merged**
