### PR TITLE
Upgrade to SI-4.2.0.RELEASE

### PR DESCRIPTION
**Pull request by artembilan**
And SI-Java-DSL-1.1.0.M2

### CODE REVIEW

**Comment by artembilan** [comment]
Updated to DSL-1.1.0.RELEASE

**Comment by artembilan** [comment]
Merging as the simple change...

**Comment by garyrussell** [comment]
Hmmm - travis failure?

**Comment by artembilan** [comment]
Right, because I pushed that before `promoting`.

**Pull request merged**
