### PR TITLE
Si3.0.x

### PR DESCRIPTION
**Pull request by lillany**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lillany Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration-samples&pullRequestId=211)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration-samples&pullRequestId=211) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by garyrussell** [comment]
What are you trying to do? This is completely invalid.

**Comment by artembilan** [comment]
@lillany ,

How have you reached this?
That's already not a first time people raise similar PRs to merge branches for old versions to master.
So, that is really confusing what makes you to do that?

**Comment by lillany** [comment]
Hi.
Sorry it was a mistake. Doing to many things at the same time.
I wasn't looking where I was and clicked the "green button" thinking it was
clone button.
When it showed error I realized I'm not on the right branch.

**Pull request closed without merging**
