### PR TITLE
Typo Gardle -> Gradle

### PR DESCRIPTION
**Pull request by cirosantilli**

### CODE REVIEW

**Comment by artembilan** [comment]
Thank you for finding that and for the fix anyway.
But we can't accept the patch without the CLA signing confirmation: https://github.com/spring-projects/spring-integration-samples/wiki

**Comment by cirosantilli** [comment]
I've tried to sign it, let me know if it didn't work.

Even PRs have boilerplate in the Java world :)

**Comment by artembilan** [comment]
> I've tried to sign it, let me know if it didn't work.

You had to receive a confirmation email with CLA Number.

From other side it's not an issue and we can fix it for you, but there won't be your commit in the project.

> Even PRs have boilerplate in the Java world

Nothing specific: just some rules of Open Source

**Comment by cirosantilli** [comment]
I've received the email. Do I need to do something else?

**Comment by artembilan** [comment]
No, that's fine.
Thank you for the contribution.
Merging you PR...

For the future, please, follow with those Contribution rules: "JIRA first!" is good way to start.

**Comment by artembilan** [comment]
Merged as :https://github.com/spring-projects/spring-integration-samples/commit/b32cd1edda288ef22a4d5660f08e20c318d75cc2
with additional fix to the same typo in other places :smile:

**Comment by cirosantilli** [comment]
I take back what I've said about Java: GNU requires you to send them a physical letter :-)

**Pull request closed without merging**
